### ISSUE TITLE
Multiple Snap Drop Zones

### ISSUE THREAD

**Issue by olanord** [thestonefox/VRTK#1160]
### Environment
VRTK Version 3.1.0
Unity 5.6.0f3
Simulator / Vive

### Steps to reproduce
Create multiple objects with Snap Drop Zones defined and make them close or overlapping each other

### Expected behavior
Only one drop zone should be highlighted, perhaps the one with shortest absolute distance to the grabbed object's pivot?  Of course you can always have small drop zones, but you can argue that if you are grabbing a large object that will still trigger multiple drop zones.
***or (i cant see any use cases for this though) you can checkbox whether you want multiple highlighted or not. 

### Current behavior
Multiple possible drop zones are being highlighted and as a user you don't know where your object will go.

**Comment by thestonefox** [comment]
I think this has been resolved in the latest github master version.

I'd recommend downloading the github master version and seeing if it solves your problem.

**Comment by olanord** [comment]
Thanks for the reply. will confirm shortly.

**Comment by Darkroll76** [comment]
Hi,

I know that this "issue" was closed a long time ago but I'm looking for the same behaviour. Which is to highlight only one SnapDropZone when the interactable Object collide with several SnapDropZone at the same time.

Did you figure out how to do it ? Because I tried with the last master version and the last release (3.3.0-alpha) and It seems that these features still not available.

Thanks ;)
